version: 0.2

env:
  variables:
    BOOK_VERSIONS: "json"
    NAME: "string"
    RELEASE_ID: "string"

phases:
  pre_install:
    commands:
      - cd spa-design/ssr-react/
  install:
    commands:
      - yarn
  pre_build:
    commands:
      - yarn build:clean
  build:
    commands:
      - yarn render
  post_build:
    commands:
      - aws s3 sync build/ s3://openstax-dev-sandbox-unicorn/$(RELEASE_ID)
