version: 0.2

env:
  variables:
    BOOK_VERSIONS: "json"
    NAME: "string"
    RELEASE_ID: "string"

phases:
  install:
    commands:
      - cd spa-design/ssr-react/
      - npm install -g yarn
      - yarn
  pre_build:
    commands:
      - yarn build:clean
  build:
    commands:
      - docker-compose run render
  post_build:
    commands:
      - aws s3 sync --content-type 'text/html' build/ s3://openstax-dev-sandbox-unicorn/$RELEASE_ID
