version: '3.5'
services:
  renderer:
    image: "node:10"
    volumes:
      - .:/code
    working_dir: /code
    command: node renderer/dist/renderer.js
    networks:
      unicorn:
    depends_on:
      - nginx
  nginx:
    image: 'nginx'
    networks:
      unicorn:
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/code/static
    ports:
      - "3015:80"
networks:
  unicorn:
