version: '3.5'
services:
  server:
    image: "node:10-slim"
    volumes:
      - .:/code
    working_dir: /code
    command: yarn serve
    networks:
      unicorn:
    ports:
      - "3012:3012"
  nginx:
    image: 'nginx'
    networks:
      unicorn:
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/code/static
      - ./server/cache/html:/code/cache
    ports:
      - "3015:80"
networks:
  unicorn:
