pipeline {
  agent {
    docker {
      image 'node:10'
      args '--privileged'
    }
  }
  parameters {
      string(name: 'RELEASE_ID')
      string(name: 'BOOK_VERSIONS', defaultValue: '{"Ax2o07Ul": "14.2"}')
  }
  stages {
    stage('build') {
      environment {
        HOME = "${env.WORKSPACE}"
        BOOK_VERSIONS = "${params.BOOK_VERSIONS}"
      }
      steps {
        sh 'curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose'
        sh 'chmod a+x ~/docker-compose'
        sh 'cd spa-design/ssr-react/ && yarn'
        sh 'cd spa-design/ssr-react/ && yarn build:clean'
        sh 'cd spa-design/ssr-react/ && ~/docker-compose run render'
      }
    }
    stage('upload') {
      steps {
        s3Upload(file: 'spa-design/ssr-react/build', bucket: 'openstax-dev-sandbox-unicorn', path: "${params.RELEASE_ID}/", contentType: 'text/html')
      }
    }
  }
}
