pipeline {
  agent {
    docker { image 'node:10' }
  }
  parameters {
      string(name: 'RELEASE_ID')
      string(name: 'BOOK_VERSIONS', defaultValue: '{"Ax2o07Ul": "14.2"}')
  }
  stages {
    stage('build') {
      environment {
        BOOK_VERSIONS = "${params.BOOK_VERSIONS}"
      }
      steps {
        sh 'cd spa-design/ssr-react/ && yarn'
        sh 'cd spa-design/ssr-react/ && yarn build:clean'
        sh 'cd spa-design/ssr-react/ && docker-compose run render'
      }
    }
    stage('upload') {
      steps {
        s3Upload(file: 'spa-design/ssr-react/build', bucket: 'openstax-dev-sandbox-unicorn', path: "${params.RELEASE_ID}/", contentType: 'text/html')
      }
    }
  }
}
